### PR TITLE
feat: support launch editor UI

### PR DESCRIPTION
**Pull request by Ricbet**
### Types

- [x] 🎉 New Features

### <samp>🤖 Generated by Copilot at 80e38a7</samp>

*  Rename `debug-schema-updater` module to `debug-schema-manager` and make `update` method public ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-bd20c679a84cdee80394805629f636606762fed319dd812d30c17e46215521a8L4-R4), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-bd20c679a84cdee80394805629f636606762fed319dd812d30c17e46215521a8L12-R12), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-bd20c679a84cdee80394805629f636606762fed319dd812d30c17e46215521a8L22-R22), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-bd20c679a84cdee80394805629f636606762fed319dd812d30c17e46215521a8L41-R42), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-9c0ef30acc35a1db8627dff9e509ebf17d309db8175a75e167a4614fe48affb1))
*  Add `launchDefaultSchemaUri` and `launchExtensionSchemaUri` constants for different debug scenarios and use them instead of string literals ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-3c78853637bd4f37b7541026444e751a0505bbb992a41a7a3c102c078a5b52daR55), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-3c78853637bd4f37b7541026444e751a0505bbb992a41a7a3c102c078a5b52daL613-R613), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-bd20c679a84cdee80394805629f636606762fed319dd812d30c17e46215521a8L4-R4), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-bd20c679a84cdee80394805629f636606762fed319dd812d30c17e46215521a8L41-R42), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-b4917f8b085ffcc2adc30bf66676c474120c21655b97da9388e795f569bd4f51R1-R5))
*  Remove unused `launchSchemaUri` import from `debug-contribution` module ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-3c78853637bd4f37b7541026444e751a0505bbb992a41a7a3c102c078a5b52daL43))
*  Add `LaunchResourceProvider` class to provide custom resource for launch view editor component ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-469d2164fd977fac513d47f5fdae2bc3ec04d5896e3f576b075504a9c0e981afL1-R79))
*  Add `LaunchPreferencesContribution` class to implement preference contribution, configuration, and editor contribution interfaces and register resource provider and editor component for launch view ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-469d2164fd977fac513d47f5fdae2bc3ec04d5896e3f576b075504a9c0e981afL1-R79))
*  Add `LaunchViewContainer` component and subcomponents to render launch view editor with split panel, debug configuration list, and configuration details ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-86ff74b03299d60f6ecd1dff7353a7b788b4cf82b31a23b34121a6db5b32b00bR1-R127))
*  Add `launch.module.less` module to define styles for launch view editor and subcomponents ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-1c9f4efbfc56bf5e861ebb6f10ddd4b5e01574289aceee3140b103097513ca47R1-R91))
*  Modify `uri` parameter of `workbenchEditorService.open` method call in `DebugConfigurationManager` class to use custom scheme `launch_view_scheme` for launch view editor ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-b27035a578a9c21d5dc65a6ee51452716d34fbb1346ff4a85e467c876245bd57L364-R364))
*  Replace `more` prop with `menu` prop for `Button` component and add `visible` prop to `Dropdown` component ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-d7a7249cdd571803b98fdd09650036566a355a402a68a58043a018acf0970ddbL130-R144))
*  Add `moreVisible` and `placement` props to `MoreActionProps` interface and pass them to `Dropdown` component inside `Button` component ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-d7a7249cdd571803b98fdd09650036566a355a402a68a58043a018acf0970ddbR31-R32), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-d7a7249cdd571803b98fdd09650036566a355a402a68a58043a018acf0970ddbR101-R102))
*  Import `Placement` type from `dropdown` component and export it from `button` component ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-d7a7249cdd571803b98fdd09650036566a355a402a68a58043a018acf0970ddbR5), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-137b46493d6ed15e73c577a29be3a65ee7a4080b8c6c8cab741e9edda1398c8aL10-R10))
*  Add `LabelMenuItemNode` class to represent menu item with label only ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-beecdc3a038f11f0e6805f7ddeff3ca7835f0023a68a08d5a85e3f2b6e6c4cfaR204-R215))
*  Modify `registerDebuggers` method of `DebuggersContributionPoint` class to use `debugSchemaManager.update` method instead of `debugSchemaUpdater.update` method ([link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-eb53d7160c7f5f8b3a65cf79baa4c9d4217f90c9f3be4b563a8f3338e0073e50L13-R13), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-eb53d7160c7f5f8b3a65cf79baa4c9d4217f90c9f3be4b563a8f3338e0073e50L193-R194), [link](https://github.com/opensumi/core/pull/2574/files?diff=unified&w=0#diff-eb53d7160c7f5f8b3a65cf79baa4c9d4217f90c9f3be4b563a8f3338e0073e50L211-R211))

image

### <samp>🤖 Generated by Copilot at 80e38a7</samp>

This pull request adds a new feature to the `Button` component to support a dropdown menu, and improves the schema management and editor for the `debug` component. It renames and refactors the `debug-schema-updater` module to `debug-schema-manager`, and introduces new modules for the launch view editor component, the launch schema URIs, and the label menu item node. It also updates the references and styles for the affected modules.

### CODE REVIEW

**Comment by erha19** [comment]
@Ricbet  几个可以优化的地方，看是否要在这个提交里一起实现：

1. 初次打开时，可以默认选中一下配置第一项，这样不会出现 NoConfigurations 的情况
image

2. 样式上：
     - No Configurations 左侧可以适当加一点左边距
     - “Add Configuration” 按钮底部可以适当增加下边距
     - 右侧编辑表单列表同上，底部可增加下边距
     - 打开编辑内容左侧按钮无 “选中态”
image

3. 可能的优化点

- 对于 variables 后续可以在这里直接帮用户展示出来，一些用户也会疑惑具体指代内容
- 如：[变量 Variable Selection] [文件  Input] ，然后在下面一行展示具体指代文本路径
- image

**Comment by Ricbet** [comment]
1、2 我优化一下，3 后续再优化

**Comment by Ricbet** [comment]
image

- [x] 默认选中第一个配置
- [x] 新增选中态
- [x] 优化部分样式（No Configurations 左侧增加边距，Add Configurations 底部增加边距，右侧add configurations item 底部增加边距）

**Review by erha19 — APPROVED** [review]
LGTM

**Pull request merged**
