### PR TITLE
chore: remove useless people name

### PR DESCRIPTION
**Pull request by erha19**
### Types

- [x] 🧹 Chores

### CODE REVIEW

**Comment by lengthmin** [comment]
https://github.com/opensumi/core/blob/chore/remove-useless-people-name/packages/core-browser/src/style/variable.less#L10

这还有俩名字

**Comment by erha19** [comment]
> https://github.com/opensumi/core/blob/chore/remove-useless-people-name/packages/core-browser/src/style/variable.less#L10
> 
> 这还有俩名字

@lengthmin 样式相关的在这个 PR 里面处理了 https://github.com/opensumi/core/pull/238

**Review by Ricbet — APPROVED** [review]

**Review by Aaaaash — APPROVED** [review]
LGTM

**Pull request merged**
