### PR TITLE
fix: call stack stop at incorrect line because call frame with sameid

### PR DESCRIPTION
**Pull request by geekeren**
### Types

- [ ] 🎉 New Features
- [x] 🐛 Bug Fixes
- [ ] 📚 Documentation Changes
- [ ] 💄 Code Style Changes
- [ ] 💄 Style Changes
- [ ] 🪚 Refactors
- [ ] 🚀 Performance Improvements
- [ ] 🏗️ Build System
- [ ] ⏱ Tests
- [ ] 🧹 Chores
- [ ] Other Changes

### Background or solution

https://github.com/opensumi/core/issues/2465

### Changelog
当前 frame存在ID 相同时 为其设置一个 uuid

### CODE REVIEW

**Comment by erha19** [comment]
@geekeren 发布需要基于 opesumi/core 切出来的分支才行，个人分支不支持 publish

**Comment by geekeren** [comment]
@erha19 我有权限从你们的仓库切分支吗

**Comment by erha19** [comment]
@geekeren 有的，给你加进 contributor 了

**Comment by geekeren** [comment]
> @geekeren 有的，给你加进 contributor 了

有邀请吗 没收到通知

**Pull request closed without merging**
