### PR TITLE
fix: clear tree node cache after the tree node is disposed

### PR DESCRIPTION
**Pull request by xkaede**
### Types

- [ ] 🐛 Bug Fixes

### <samp>🤖 Generated by Copilot at 6349cdb</samp>

*  Dispose the root node of the tree when the tree or the tree service is disposed ([link](https://github.com/opensumi/core/pull/3109/files?diff=unified&w=0#diff-f29ee99a9c13c2068cbbd3db54b2b534e175f5ba6e84ae0cdadadee2a5ecd80bR18), [link](https://github.com/opensumi/core/pull/3109/files?diff=unified&w=0#diff-2435fb9fb663600404d30dfdfbcce6633ef04d1e96544bc99770ea8ca6c1cb2bL181-R181), [link](https://github.com/opensumi/core/pull/3109/files?diff=unified&w=0#diff-2435fb9fb663600404d30dfdfbcce6633ef04d1e96544bc99770ea8ca6c1cb2bR195))
*  Add a super.dispose() call to the BasicTreeService class to dispose the parent class resources ([link](https://github.com/opensumi/core/pull/3109/files?diff=unified&w=0#diff-1f7540db9587a83872a41a538717851bbe3384156bfd544711ee7b700fcf1b12R205))
*  Remove the node from the static maps of idToTreeNode and pathToTreeNode when the node is disposed, removed, or refreshed ([link](https://github.com/opensumi/core/pull/3109/files?diff=unified&w=0#diff-e06f6e62a0aec13e178cf8da9849199b77cb52168b1f794591f7ced4a2e1d109R334-R335), [link](https://github.com/opensumi/core/pull/3109/files?diff=unified&w=0#diff-2f6de085e6ee0e6f5b5f1ccbc5d14d23d4cf2183c3540b14eb55e54e9b335c4bR236-R282))
*  Add a condition to the Tree class to avoid unnecessary disposal of the root node when it is not changed ([link](https://github.com/opensumi/core/pull/3109/files?diff=unified&w=0#diff-f29ee99a9c13c2068cbbd3db54b2b534e175f5ba6e84ae0cdadadee2a5ecd80bR26-R30))
*  Add the child node to the static map of pathToTreeNode when the child node is created in the CompositeTreeNode class ([link](https://github.com/opensumi/core/pull/3109/files?diff=unified&w=0#diff-e06f6e62a0aec13e178cf8da9849199b77cb52168b1f794591f7ced4a2e1d109R875))

### <samp>🤖 Generated by Copilot at 6349cdb</samp>

This pull request enhances the memory management and error handling of the tree components and services by disposing the root nodes and updating the static maps when the tree structure changes. It also adds new test cases to verify the TreeNode logic and ensure the code coverage.

### CODE REVIEW

**Comment by xkaede** [comment]
fix https://github.com/opensumi/core/issues/3096#issue-1921537793

**Review by erha19 — DISMISSED** [review]
LGTM

**Review by bytemain — DISMISSED** [review]

**Comment by erha19** [comment]
@xkaede 测试需要处理一下，同时合并一下 main 分支最新内容
image

**Review by erha19 — APPROVED** [review]

**Pull request merged**
