### PR TITLE
feat: support type hierarchy api

### PR DESCRIPTION
**Pull request by bk1012**
### Types

- [x] 🎉 New Features

### Background or solution
support vscode 1.63.2 type hierarchy api

#### 1:
sample: https://github.com/Eskibear/type-hierarchy-sample/blob/main/src/extension.ts

image

#### 2:
sample: ESLint extension (version 2.2.2)

image

### Changelog
* support vscode 1.63.2 type hierarchy api

### CODE REVIEW

**Comment by bk1012** [comment]
#579

**Comment by bk1012** [comment]
#579

**Comment by erha19** [comment]
@bk1012  Changelog 写一下

**Review by Aaaaash — APPROVED** [review]

**Pull request merged**
