### PR TITLE
feat: support set window title

### PR DESCRIPTION
**Pull request by bytemain**
### Types

- [x] 🎉 New Features

### Background or solution

close: #1721
- #1721

CleanShot 2022-10-11 at 11 55 22@2x
CleanShot 2022-10-11 at 12 00 12@2x

效果

https://user-images.githubusercontent.com/13938334/195019952-37f2fa5d-bea1-49c1-9771-7f1c819c5f0a.mp4

### Changelog

support set window title

### CODE REVIEW

**Comment by bytemain** [comment]
TODO: 要去除多个分隔符的 case

**Comment by bytemain** [comment]
效果

https://user-images.githubusercontent.com/13938334/195019952-37f2fa5d-bea1-49c1-9771-7f1c819c5f0a.mp4

**Review by yantze — APPROVED** [review]
LGTM

**Pull request merged**
