### PR TITLE
refactor: optimize framework dependency structure

### LINKED ISSUE #110: Optimize framework dependency structure
## 潜规则

1. `@opensumi/ide-core-common`  为 `@opensumi/ide-core-node` ， `@opensumi/ide-core-browser` 和 `@opensumi/ide-electron`  的共同依赖

2. 其他模块不直接依赖 `@opensumi/ide-core-common`，而是通过 `@opensumi/ide-core-node` 和 `@opensumi/ide-core-browser`  间接依赖

3.  由于前端资源一般有脚本进行打包构建，而 Node 资源一般需要直接依赖 `node_modules` ，故我们前期设计上期望模块的 Browser 层依赖放在 `DevDepedence`，而 Node 层依赖放在 `Dependence`.

4.  所有模块的构建，统一依赖 `@opensumi/ide-dev-tool` 方式引入构建依赖，如 `typescript`, `webpack` 等

5. 基于这种目录结构，如果存在多个 Browser 模块的公共依赖，放在 `@opensumi/ide-core-browser` 将能减少版本维护的烦恼，一般通过脚本 `npm run add:browser {moduleName} {depName}` 的方式添加，同理也有 `add:node` 的脚本。

6. 原则上如果模块 `common` 中只能引入 `@opensumi/ide-core-common` 中的内容，但如果该模块为纯 `Browser` 或 `Node` 模块，则允许从对应的 `@opensumi/ide-core-browser` 和 `@opensumi/ide-core-node` 中引入。

## 图示

截屏2021-12-09 上午11 49 11

### PR DESCRIPTION
**Pull request by erha19**
### Types

- [x] 🪚 Refactors

### Background or solution

fixed #110

### Changelog

optimize framework dependency structure

### CODE REVIEW

**Comment by erha19** [comment]
测试通过了

**Review by Ricbet — APPROVED** [review]

**Pull request merged**
