### PR TITLE
feat: quick-open support busy option

### PR DESCRIPTION
**Pull request by pipiiiiii**
### Types

- [x] 🎉 New Features

### Background or solution
vscode:
vscode-busy
opensumi:
opensumi-busy

### <samp>🤖 Generated by Copilot at ba50fad</samp>

*  Add a new `busy` property to various interfaces and classes related to the quick pick widget, such as `QuickOpenInputOptions`, `IQuickOpenWidget`, `IKaitianQuickOpenControllerOpts`, and `Resolved` ([link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-27adcfe43b78217fabf448b56fdd299f340097f3331147ef3307426ddcf3fa1fR250), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-27adcfe43b78217fabf448b56fdd299f340097f3331147ef3307426ddcf3fa1fR359-R362), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-ff6860d3b51c6750266e7e6434a7fd6f60f9f925ffa9601468a056d9bf050d86R50), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-586f0727f06ff3bbb7a0f6580b8b7118f4b49998d4cbc8cbda26a113e87e6029R91), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-586f0727f06ff3bbb7a0f6580b8b7118f4b49998d4cbc8cbda26a113e87e6029R99), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-6cef777676951622df1128d6b97965529c202ddb93a316c71f600449c3c9ce22R164))
*  Add a new method `updateOptions` to the `QuickOpenService` and `MonacoQuickOpenService` classes, and implement it in the `QuickOpenWidget` and `InputBoxImpl` classes, to allow updating the options of the quick pick widget, such as the busy state, without closing and reopening it ([link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-27adcfe43b78217fabf448b56fdd299f340097f3331147ef3307426ddcf3fa1fR250), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-ff6860d3b51c6750266e7e6434a7fd6f60f9f925ffa9601468a056d9bf050d86R136-R140), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-f96acf4c25fadaa5c3e1117c089f6d262a7f783d3922e1087e867c11e22773c4R203-R227), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-6cef777676951622df1128d6b97965529c202ddb93a316c71f600449c3c9ce22R64))
*  Inject the `IProgressService` to the `MonacoQuickOpenService` and `QuickOpenWidget` classes, and use it to register and dispose a progress indicator for the quick pick widget, using the `QUICKPICK_PROGRESS` ID from the `VIEW_CONTAINERS` enum ([link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-ff6860d3b51c6750266e7e6434a7fd6f60f9f925ffa9601468a056d9bf050d86L14-R18), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-ff6860d3b51c6750266e7e6434a7fd6f60f9f925ffa9601468a056d9bf050d86L71-R81), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-ff6860d3b51c6750266e7e6434a7fd6f60f9f925ffa9601468a056d9bf050d86R107), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-ff6860d3b51c6750266e7e6434a7fd6f60f9f925ffa9601468a056d9bf050d86R114),  [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-f96acf4c25fadaa5c3e1117c089f6d262a7f783d3922e1087e867c11e22773c4L3-R3), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-f96acf4c25fadaa5c3e1117c089f6d262a7f783d3922e1087e867c11e22773c4R14-R15), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-f96acf4c25fadaa5c3e1117c089f6d262a7f783d3922e1087e867c11e22773c4R58-R60), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-f96acf4c25fadaa5c3e1117c089f6d262a7f783d3922e1087e867c11e22773c4R203-R227))
*  Add a new `div` element with the `QUICKPICK_PROGRESS` ID and the `progress_bar` class to the `QuickOpenView` function, and render a `ProgressBar` component inside it, to show the progress bar element in the quick pick widget ([link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-20e4dc46b94cf72b6e1623d2b69b8567c06aaa6e5ca4d7ef7a56845bde03dff5R16-R17), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-20e4dc46b94cf72b6e1623d2b69b8567c06aaa6e5ca4d7ef7a56845bde03dff5R536-R538))
*  Add a new effect to the `QuickOpenView` function, and a new method `updateProgressStatus` to the `IQuickOpenWidget` and `QuickOpenWidget` interfaces and classes, to update the visibility of the progress bar element based on the busy state of the quick pick widget ([link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-586f0727f06ff3bbb7a0f6580b8b7118f4b49998d4cbc8cbda26a113e87e6029R116), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-20e4dc46b94cf72b6e1623d2b69b8567c06aaa6e5ca4d7ef7a56845bde03dff5R473-R476), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-f96acf4c25fadaa5c3e1117c089f6d262a7f783d3922e1087e867c11e22773c4R203-R227))
*  Add a new style rule to the `progress_bar` class, to position the progress bar element in the quick pick widget ([link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-83d1f18a11c4628e30d8e972f2e652d489166a789ef9b562b4c73367e93173c7R191-R194))
*  Initialize the `_busy` property of the `ExtQuickInput` class to `false`, and pass the `busy` property of the `opts` object to the `widget` object in the `MonacoQuickOpenService` class, to set the initial and updated busy state of the quick pick widget ([link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-535cb53d1888c004f19b7369d5b1da90462def0d39ad8d6d9d2b382ea571e80aR485), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-ff6860d3b51c6750266e7e6434a7fd6f60f9f925ffa9601468a056d9bf050d86R128), [link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-f96acf4c25fadaa5c3e1117c089f6d262a7f783d3922e1087e867c11e22773c4R153))
*  Add a new condition to the `shouldUpdate` method of the `InputBoxImpl` class, to determine whether the input box should update its options based on the busy state of the quick pick widget ([link](https://github.com/opensumi/core/pull/2579/files?diff=unified&w=0#diff-6cef777676951622df1128d6b97965529c202ddb93a316c71f600449c3c9ce22L38-R39))

#2576 

### <samp>🤖 Generated by Copilot at ba50fad</samp>

This pull request adds a new feature to the quick pick widget, which is a progress bar that indicates when the widget is busy. It modifies several files in the `quick-open` and `core-browser` packages to support updating the widget options and the progress status dynamically. It also updates the `extension` package to initialize the busy state of the widget.

* feat: quickpick support busy option
* feat: quickpick instance property change will update widget

### CODE REVIEW

**Comment by erha19** [comment]
@pipiiiiii 功能提交不进 Patch 分支，提到 main 分支吧

**Comment by pipiiiiii** [comment]
> @pipiiiiii 功能提交不进 Patch 分支，提到 main 分支吧

改好了，这个会在 2.24 发上去么

**Comment by erha19** [comment]
会在 2.24.0 版本上发布 @pipiiiiii

**Review by erha19 — APPROVED** [review]

**Pull request merged**
