### PR TITLE
refactor: update monaco editor 0.34.0

### PR DESCRIPTION
**Pull request by Aaaaash**
### Types

- [x] 🪚 Refactors

### Background or solution

https://github.com/opensumi/monaco-editor-core

- [x] https://github.com/opensumi/core/blob/refactor/monaco-editor-0.33/packages/extension/src/browser/vscode/api/main.thread.comments.ts#L414-L418
- [x] https://github.com/opensumi/core/blob/33d258f83fed364975eef5154d5b7b7b1e4e5448/packages/debug/src/browser/view/console/debug-console.service.ts#L125-L128

### Changelog
- update monaco editor 0.34.0

### CODE REVIEW

**Review by hacke2 — APPROVED** [review]
LGTM

**Comment by bytemain** [comment]
fantastic!

**Comment by life2015** [comment]
inlay hint 有偶现的问题
image

**Comment by Aaaaash** [comment]
https://github.com/opensumi/core/pull/1493

**Pull request closed without merging**
