### PR TITLE
chore: uniformly use same md5 service

### LINKED ISSUE #977: [FEATURE] 统一 md5 digest 能力
在代码库中搜索 `md5'`，还是能看到使用了各式各样方法获取 md5 值的逻辑，可以替换掉并移除相关依赖

### PR DESCRIPTION
**Pull request by iamxukai**
### Types

- [x] 🧹 Chores
### Background or solution
closes #977

### CODE REVIEW

**Comment by erha19** [comment]
@iamxukai 有冲突，你 rebase 一下 main 分支代码

**Comment by iamxukai** [comment]
> @iamxukai 有冲突，你 rebase 一下 main 分支代码

冲突解决好了

**Comment by erha19** [comment]
@iamxukai 冲突处理一下 ~

**Comment by bytemain** [comment]
```
FAIL packages/extension/__tests__/node/extension.service.client.test.ts
  ● Extension Client Serivce › language pack › should generate languagepacks.json and set VSCODE_NLS_CONFIG

    没有找到 Symbol(IHashCalculateService) 的 Provider

      28 |   get<T>(token: Token, opts?: InstanceOpts): T;
      29 |   get(arg1: any, arg2?: any, arg3?: any) {
    > 30 |     const instance = super.get(arg1, arg2, arg3);
         |                            ^
      31 |     const mockDefs = this.mockMap.get(arg1);
      32 |     if (mockDefs) {
      33 |       for (const mockDef of mockDefs) {

      at Object.noProviderError (node_modules/@opensumi/di/dist/error.js:20:12)
      at MockInjector.Object.<anonymous>.Injector.get (node_modules/@opensumi/di/dist/injector.js:190:33)
      at MockInjector.get (tools/dev-tool/src/mock-injector.ts:30:28)
      at ExtensionServiceClientImpl.get [as hashCalculateService] (node_modules/@opensumi/di/dist/decorator.js:116:51)
      at ExtensionServiceClientImpl.hashCalculateService [as convertLanguagePack] (packages/extension/src/node/extension.service.client.ts:135:25)
      at ExtensionServiceClientImpl.convertLanguagePack [as updateLanguagePack] (packages/extension/src/node/extension.service.client.ts:185:17)
      at Object.<anonymous> (packages/extension/__tests__/node/extension.service.client.test.ts:77:7)
```

这个测试用例（packages/extension/__tests__/node/extension.service.client.test.ts）需要补充一下这个 Provider，可以参考一下：[IHashCalculateService](https://github.com/opensumi/core/blob/8a433729452ba8397a553e9a886796b467774106/packages/core-common/__tests__/hash-calculate.test.ts#L8)

**Comment by iamxukai** [comment]
> 

我在 [baseInjector.ts](https://github.com/opensumi/core/pull/1003/commits/249f14acfd19588a42ef92bca82863f6f4a73d12) 中补上了

**Comment by iamxukai** [comment]
> ```
> FAIL packages/extension/__tests__/node/extension.service.client.test.ts
>   ● Extension Client Serivce › language pack › should generate languagepacks.json and set VSCODE_NLS_CONFIG
> 
>     没有找到 Symbol(IHashCalculateService) 的 Provider
> 
>       28 |   get<T>(token: Token, opts?: InstanceOpts): T;
>       29 |   get(arg1: any, arg2?: any, arg3?: any) {
>     > 30 |     const instance = super.get(arg1, arg2, arg3);
>          |                            ^
>       31 |     const mockDefs = this.mockMap.get(arg1);
>       32 |     if (mockDefs) {
>       33 |       for (const mockDef of mockDefs) {
> 
>       at Object.noProviderError (node_modules/@opensumi/di/dist/error.js:20:12)
>       at MockInjector.Object.<anonymous>.Injector.get (node_modules/@opensumi/di/dist/injector.js:190:33)
>       at MockInjector.get (tools/dev-tool/src/mock-injector.ts:30:28)
>       at ExtensionServiceClientImpl.get [as hashCalculateService] (node_modules/@opensumi/di/dist/decorator.js:116:51)
>       at ExtensionServiceClientImpl.hashCalculateService [as convertLanguagePack] (packages/extension/src/node/extension.service.client.ts:135:25)
>       at ExtensionServiceClientImpl.convertLanguagePack [as updateLanguagePack] (packages/extension/src/node/extension.service.client.ts:185:17)
>       at Object.<anonymous> (packages/extension/__tests__/node/extension.service.client.test.ts:77:7)
> ```
> 
> 这个测试用例（packages/extension/**tests**/node/extension.service.client.test.ts）需要补充一下这个 Provider，可以参考一下：[IHashCalculateService](https://github.com/opensumi/core/blob/8a433729452ba8397a553e9a886796b467774106/packages/core-common/__tests__/hash-calculate.test.ts#L8)

我在 [baseInjector.ts](https://github.com/opensumi/core/pull/1003/commits/249f14acfd19588a42ef92bca82863f6f4a73d12) 中补上了

**Comment by iamxukai** [comment]
```Summary of all failing tests
FAIL packages/extension/__tests__/node/extension.service.client.test.ts
  ● Extension Client Serivce › language pack › should generate languagepacks.json and set VSCODE_NLS_CONFIG

    Please call #initialize first!

      46 |   calculate(content: IDataType): string {
      47 |     if (!this.initialized) {
    > 48 |       throw new Error('Please call #initialize first!');
         |             ^
      49 |     }
      50 |     const hash = this.cachedCalculator!.calculate(content);
      51 |     return hash;

      at HashCalculateServiceImpl.calculate (packages/core-common/src/hash-calculate/hash-calculate.ts:48:13)
      at ExtensionServiceClientImpl.calculate [as convertLanguagePack] (packages/extension/src/node/extension.service.client.ts:135:46)
      at ExtensionServiceClientImpl.convertLanguagePack [as updateLanguagePack] (packages/extension/src/node/extension.service.client.ts:185:17)
      at Object.<anonymous> (packages/extension/__tests__/node/extension.service.client.test.ts:77:7)

**Review by bytemain — APPROVED** [review]

**Pull request merged**
